### ISSUE TITLE
Make using gofmt mandatory

### ISSUE THREAD

**Issue by rexim** [tsoding/snitch#10]
derived from #8 
depends on #7 

https://golang.org/cmd/gofmt/

**Comment by rexim** [comment]
@fabulousduck is it possible to run gofmt on CI and fail the build if the code doesn't follow the required format?

**Comment by fabulousduck** [comment]
something like this https://github.com/bwmarrin/discordgo/blob/master/.travis.yml#L11 ?

**Comment by rexim** [comment]
@fabulousduck perfect! Thank you so much!
