### ISSUE TITLE
Populate git commit message

### ISSUE THREAD

**Issue by TheKnarf** [tsoding/snitch#12]
It might be nice to populate the git commit message with the current issue ID so that when you write `git commit` and it opens your standard editor (usually vim) it would already be prepopulated with the issue number.

**Comment by rexim** [comment]
@TheKnarf If you're following [git-flow] (or any kind of modification of it) you probably work an separate issues in separate branches. I usually go to the extent of calling my branches with straight up the number of the issue: `git checkout -b 42`. So you can easily set up a [prepare-commit-msg] hook that inserts the current branch name into the template of the commit message. You can find more info in [this SO question][so-question] for example.

So this issue kinda feels like outside of the scope of this project. What do you think?

[git-flow]: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
[prepare-commit-msg]: https://git-scm.com/docs/githooks#_prepare_commit_msg
[so-question]: https://stackoverflow.com/a/4091005/2951870

**Comment by TheKnarf** [comment]
Personally, I don't follow `git-flow` on solo projects.

I'd love if `snitch` had the option to be configured to call `prepare-commit-msg` with a given issue number and with the description of the issue as a part of the commit (but maybe in a comment).

The way I imagine it working is something like:

```
$ snitch workon 12
$ git commit
Work towards #12

# Issue 12:
# Populate git commit message
# 
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
```

That way (in combination with issue #11) I never have to leave the terminal to work on issues. And it should work either you use `git-flow` or not.

**Comment by rexim** [comment]
@TheKnarf this still sounds outside of the scope of this project. Snitch is a simple tool that collects TODOs in the source code and reports them as GitHub issues. Your idea is great for a separate tool though.

**Comment by TheKnarf** [comment]
If you don't want this functionality in snitch then feel free to close this and the related issue #11.
