### ISSUE TITLE
Support github credentials via environment variables

### ISSUE THREAD

**Issue by jspaulsen** [tsoding/snitch#139]
Environment variables provide an alternative (one I personally prefer; plus ini is butt) for storing authentication credentials.

If this is acceptable, perhaps a strategy of first attempting to use environment variables and then attempting to load the configuration ini?

**Comment by rexim** [comment]
@jspaulsen Sure, sounds good to me. 

Unfortunately, I do not develop snitch actively anymore. But I'm open for Pull Request. ;)

**Comment by rexim** [comment]
Resolved by #140
