### ISSUE TITLE
Snitch list does not work with repos without remote

### ISSUE THREAD

**Issue by rexim** [tsoding/snitch#142]
Related to #90 

### Steps to reproduce

```console
$ git init foo
$ cd foo
$ echo "TODO: foo" > foo.c
$ snitch list --unreported
```

### Observed

Error: ` does not match github.com[:/]([-\w]+)\/([-\w]+)(.git)?`

### Expected

List of unreported TODOs. You don't really need an actual GitHub repo for that.

**Comment by aod** [comment]
Can be closed. Same goes with #90.

![image](https://user-images.githubusercontent.com/24858380/74522009-aab5b300-4f1a-11ea-9c91-269aebb369a0.png)

**Comment by rexim** [comment]
@aod thanks! I remember fixing it while working on something else. Completely forgot I had an issue for that! :dagger: 

#90 should not be closed yet. It's about completely different thing. Added more information there.
