### ISSUE TITLE
Keep repository in IssueAPI structure?

### ISSUE THREAD

**Issue by mfocko** [tsoding/snitch#155]
Since the repository is matched against host assigned to token, there is no particular reason to keep it outside of credentials?

Only place it's used (outside the GET and POST against service API) is:
1. printing issue link (can be extracted to something like `getRepoAddress`)
1. printing detected project (can be resolved same way as issue link)

**Comment by rexim** [comment]
@mfocko yeah, I had exactly the same thoughts while reviewing #154. I like that idea. Maybe even go further and rename `IssueAPI` to `Repo`? What do you think?

**Comment by mfocko** [comment]
@rexim Sounds OK, I'll resolve it later

**Comment by rexim** [comment]
@mfocko #154 is already merged btw. Feel free to make a separate issue.

**Comment by rexim** [comment]
Resolved by https://github.com/tsoding/snitch/pull/158#issuecomment-535287548
