### ISSUE TITLE
Support multiple GitLab hosts from environment variables

### ISSUE THREAD

**Issue by rexim** [tsoding/snitch#157]
introduced in #154

**Comment by mfocko** [comment]
comma-separated string like `GITLAB_PRIVATE_TOKEN="host:token,host:token"`?

**Comment by rexim** [comment]
@mfocko I don't really know. I don't even use the environment variables configuration. It was introduced in #139 by @jspaulsen 

@jspaulsen is the format ok for you?

**Comment by jspaulsen** [comment]
@rexim I don't see any immediate issues with this formatting, so :+1:
