### ISSUE TITLE
Use Go modules

### ISSUE THREAD

**Issue by aod** [tsoding/snitch#169]
Use Go’s new dependency management system. ~~This allows the project to be outside of the GOPATH so you can clone the project wherever.~~ Also it makes dependency version information explicit and easier to manage.

**Comment by rexim** [comment]
@aoktayd I have no idea what you are talking about. I always git cloned the project to arbitrary places and never had to do anything with GOPATH :thinking:

**Comment by aoktayd** [comment]
Hold on... what? Before they added go modules you couldn't even build the project outside your GOPATH. I guess you can do this now 🤷‍♂.
