### ISSUE TITLE
Bug: trailing "-->" for HTML comments

### ISSUE THREAD

**Issue by valerius21** [tsoding/snitch#208]
How to reproduce:

1. have an HTML file present in git.
2. add a comment with `<!-- TODO: xxx -->` in it
3. `snitch report`
4.  "-->" appears in the issue title.

Thanks!

**Comment by rexim** [comment]
@valerius21 please use a custom title transformation to get rid of the trailing `-->` https://github.com/tsoding/snitch#issue-title-transformation
